name: MQ-ViTAE_p312_venv
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - pytorch=2.4.0
  - pytorch-cuda=11.8
  - pytorch-msssim=1.0.0
  - torchvision=0.19.0
  - mpmath=1.3.0
  - matplotlib=3.8.4
  - pillow=10.4.0
  - pip=24.0
  - pandas=2.2.2
  - numpy=1.26.4
  - scikit-learn=1.5.1
  - scipy=1.13.1
  - typing_extensions=4.11.0
  - typing_utils=0.1.0
  - timm=1.0.14
  - pip:
      - argparse==1.4.0
      - tqdm==4.66.5
      - transformers==4.44.2
      - typing-inspect==0.9.0
      - vector-quantize-pytorch==1.17.1
      - zetascale==2.7.3
      - einops==0.8.0
      - einops-exts==0.0.4
